spring:
  profiles:
    active: dev

mybatis-flex:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.zeroxn.bbs.core.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS