spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://10.10.10.10:5432/school_bbs'
    username: postgres
    password: admin
  rabbitmq:
    host: 10.10.10.10
    port: 5672
    virtual-host: /
    username: root
    password: admin
powerjob:
  worker:
    app-name: bbs-task
    server-address: 10.10.10.10:7700
    store-strategy: memory
    protocol: http
baidu:
  app-id: '41596274'
  app-key: '5qPg3mUZ5CB5HSKuueEBsqaF'
  secret-key: 'acnSBKEBSBTtL98SlgpFOZqGGhg6ngKO'
  grant-type: 'client_credentials'