spring:
  profiles:
    active: test

mybatis-flex:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.zeroxn.bbs.core.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

xunfei:
  analytics:
    request-url: 'https://ltpapi.xfyun.cn/v1/ke'
    appid: '49681549'
    api-key: '919495c6d603fd43d9724e94d6056a4c'
    type: 'dependent'
analysis:
  size: 6