spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://10.10.10.12:5432/school_bbs'
    username: postgres
    password: admin
  rabbitmq:
    host: 10.10.10.12
    port: 5672
    virtual-host: /
    username: root
    password: admin

powerjob:
  worker:
    app-name: bbs-task
    server-address: 10.10.10.12:7700
    store-strategy: memory
    protocol: http