spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://10.10.10.10:5432/school_bbs'
    username: postgres
    password: admin

wechat:
  appid: asdasdasd
  secret: asdasdasd

jwt:
  expire-hours: 48
  audience: school_bbs
  issuer: school_bbs
  random-key: false
  public-key-path: classpath:certs/public.pem
  private-key-path: classpath:certs/private.pem

qiniu:
  access-key: '7ljXDMVJ50r9QHHvqqLT191IWDn8qy3bU3gCwMdY'
  secret-key: 'CymD_ID_-__AiYbnHbUkIMe1FTFXCnfC52NVEZG2'
  bucket: 'img-sr'
  bucket-domain: 'https://image.qiniu.vnc.ink/'