server:
  port: 8040
spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 40MB
logging:
  config: classpath:logback-spring.xml
  pattern:
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/api-docs
  packages-to-scan:
    - com.zeroxn.bbs.web.controller
    - com.zeroxn.bbs.core.entity
    - com.zeroxn.bbs.web.dto
mybatis-flex:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.zeroxn.bbs.core.entity
  configuration:
    map-underscore-to-camel-case: true